apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-istio-tracing-client
  namespace: istio-trace-work
  labels:
    app: otel-istio-tracing-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-istio-tracing-client
  template:
    metadata:
      labels:
        app: otel-istio-tracing-client
    spec:
      containers:
        - name: otel-istio-tracing-client
          image: ghcr.io/keisukesakasai/app/otel-istio-tracing-client:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:  
            - name: LOG_LEVEL
              value: "info"
            - name: APP_VERSION
              value: "v1.0.0"
            - name: SERVICE_NAME
              value: "otel-istio-tracing-client"
            - name: OTEL_COLLECTOR_ADDRESS
              value: sample-collector.observability.svc.cluster.local:4317"
            - name: SLEEP
              value: "5"
            - name: SERVER_ADDRESS
              value: "otel-istio-tracing-server.istio-trace-work.svc.cluster.local"
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 100Mi                
---
apiVersion: v1
kind: Service
metadata:
  name: otel-istio-tracing-client
  namespace: istio-trace-work
spec:
  selector:
    app: otel-istio-tracing-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080              